name: ci
on: [push, pull_request]
jobs:
  validate:
    name: Build and validate the project.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      # run any `bun` or `bunx` command
      - run: bun install
      #  - uses: withastro/action-studio@main
      - run: bun validate
  scc_job:
    name: A job to count the lines of code.
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Get the lines of code.
      #   id: scc
      #   run: scc --ci --format-multi tabular:stdout,html:reports/code-stats-ci.html,html-table:reports/code-stats-table-ci.html,json2:reports/code-stats-ci.json -i js,ts,jsx,tsx,c#,html,css
          # with:
          #   args: ${{ env.workspace }} -i js,ts,jsx,tsx,c#,html,css
