name: ci
on: [push, pull_request]
jobs:
  my-job:
    name: my-job
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      
      # run any `bun` or `bunx` command
      - run: bun install
    #  - uses: withastro/action-studio@main
      - run: bun validate
      # - run: bun db-setup
      # - run: bun run src/snippets/rewriter.ts
      # - run: bun run src/inliner/inliner.ts
      # - run: bun run src/snippets/html-rewriter.ts
